/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import controller.ProjectController;
import java.util.Date;
import javax.swing.JOptionPane;
import model.Project;

/**
 *
 * @author usuario
 */
public class ProjectDialogScreen extends javax.swing.JDialog {
    ProjectController controller;
    public ProjectDialogScreen(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        controller = new ProjectController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelToolBarDialog = new javax.swing.JPanel();
        jLabellToolBarDialogTitle = new javax.swing.JLabel();
        lToolBarDialogAdd = new javax.swing.JLabel();
        jPanellToolBarDialogInputs = new javax.swing.JPanel();
        jLabelDialogNameInputProject = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jLabelDialogDescInputProject = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDesc = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(380, 380));

        jPanelToolBarDialog.setBackground(new java.awt.Color(0, 153, 102));
        jPanelToolBarDialog.setMinimumSize(new java.awt.Dimension(380, 380));
        jPanelToolBarDialog.setPreferredSize(new java.awt.Dimension(400, 60));

        jLabellToolBarDialogTitle.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabellToolBarDialogTitle.setForeground(java.awt.Color.white);
        jLabellToolBarDialogTitle.setText("Projeto");

        lToolBarDialogAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mais.png"))); // NOI18N
        lToolBarDialogAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lToolBarDialogAddMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelToolBarDialogLayout = new javax.swing.GroupLayout(jPanelToolBarDialog);
        jPanelToolBarDialog.setLayout(jPanelToolBarDialogLayout);
        jPanelToolBarDialogLayout.setHorizontalGroup(
            jPanelToolBarDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelToolBarDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabellToolBarDialogTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lToolBarDialogAdd)
                .addContainerGap())
        );
        jPanelToolBarDialogLayout.setVerticalGroup(
            jPanelToolBarDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelToolBarDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lToolBarDialogAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabellToolBarDialogTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanellToolBarDialogInputs.setBackground(java.awt.Color.white);

        jLabelDialogNameInputProject.setText("Nome");

        jLabelDialogDescInputProject.setText("Descrição");

        jTextAreaDesc.setColumns(20);
        jTextAreaDesc.setRows(5);
        jTextAreaDesc.setMinimumSize(new java.awt.Dimension(100, 100));
        jTextAreaDesc.setName(""); // NOI18N
        jScrollPane1.setViewportView(jTextAreaDesc);

        javax.swing.GroupLayout jPanellToolBarDialogInputsLayout = new javax.swing.GroupLayout(jPanellToolBarDialogInputs);
        jPanellToolBarDialogInputs.setLayout(jPanellToolBarDialogInputsLayout);
        jPanellToolBarDialogInputsLayout.setHorizontalGroup(
            jPanellToolBarDialogInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanellToolBarDialogInputsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanellToolBarDialogInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldName)
                    .addComponent(jLabelDialogNameInputProject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelDialogDescInputProject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanellToolBarDialogInputsLayout.setVerticalGroup(
            jPanellToolBarDialogInputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanellToolBarDialogInputsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelDialogNameInputProject)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelDialogDescInputProject)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelToolBarDialog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanellToolBarDialogInputs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelToolBarDialog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanellToolBarDialogInputs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lToolBarDialogAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lToolBarDialogAddMouseClicked
        try {
            Project project = new Project();
            project.setName(jTextFieldName.getText());
            project.setDescription(jTextAreaDesc.getText());
            project.setUpdated_at(new Date());
            controller.save(project);
            JOptionPane.showMessageDialog(rootPane,"Projeto salvo com sucesso"); 
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane,e.getMessage());
        }
        this.dispose();  
    }//GEN-LAST:event_lToolBarDialogAddMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Java swing".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjectDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjectDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjectDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjectDialogScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ProjectDialogScreen dialog = new ProjectDialogScreen(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelDialogDescInputProject;
    private javax.swing.JLabel jLabelDialogNameInputProject;
    private javax.swing.JLabel jLabellToolBarDialogTitle;
    private javax.swing.JPanel jPanelToolBarDialog;
    private javax.swing.JPanel jPanellToolBarDialogInputs;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaDesc;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JLabel lToolBarDialogAdd;
    // End of variables declaration//GEN-END:variables
}
